CREATE DATABASE TICKETING;
\c TICKETING

CREATE SEQUENCE seq_zone;
CREATE SEQUENCE seq_promo;
CREATE SEQUENCE seq_Disposition;
CREATE SEQUENCE seq_Event;
CREATE SEQUENCE seq_Reservation;


CREATE TABLE ZONES(
    idZone VARCHAR(200) PRIMARY KEY,
    nom VARCHAR(200) NOT NULL
);

CREATE TABLE EVENT(
    idEvent VARCHAR(200) PRIMARY KEY,
    nom VARCHAR(200) NOT NULL,
    dateEvent TIMESTAMP NOT NULL
);

ALTER TABLE EVENT ADD COLUMN VARCHAR;

CREATE TABLE PROMOTION(
    idPromotion VARCHAR(200) PRIMARY KEY,
    idEvent VARCHAR(200) REFERENCES EVENT(idEvent),
    idZone VARCHAR(200) REFERENCES ZONES(idZone),
    promotion INT DEFAULT 0,
    debutPromotion TIMESTAMP DEFAULT NULL,
    FinPromotion TIMESTAMP DEFAULT NULL
);

CREATE TABLE DISPOSITIONPLACE(
    idDisposition VARCHAR(200) PRIMARY KEY,
    idEvent VARCHAR(200) REFERENCES EVENT(idEvent),
    idZone VARCHAR(200) REFERENCES ZONES(idZone),
    debut INT NOT NULL,
    fin INT NOT NULL
);

ALTER TABLE DISPOSITIONPLACE ADD COLUMN idPromotion VARCHAR(200) REFERENCES PROMOTION(idPromotion);

CREATE TABLE RESERVATION(
    idReservation VARCHAR(200) PRIMARY KEY,
    idEvent VARCHAR(200) REFERENCES EVENT(idEvent),
    idZone VARCHAR(200) REFERENCES ZONES(idZone),
    dateReservation TIMESTAMP,
    numero INT
);

CREATE TABLE PAYEMENT(
    idPayement VARCHAR(200) PRIMARY KEY,
    idEvent VARCHAR(200) REFERENCES EVENT(idEvent),
    idZone VARCHAR(200) REFERENCES ZONES(idZone),
    datePayement TIMESTAMP,
    numero INT
);

CREATE TABLE PLACEPAYE(
    idEvent VARCHAR(200) REFERENCES EVENT(idEvent),
    idZone VARCHAR(200) REFERENCES ZONES(idZone),
    dateReservation TIMESTAMP,
    numero INT
);